# Generated by Django 4.2.6 on 2023-10-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'بارگذاری عکس',
                'verbose_name_plural': 'بارگذاری عکس ها',
            },
        ),
        migrations.CreateModel(
            name='FireFightingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(upload_to='media/')),
                ('specification', models.CharField(blank=True, max_length=200, null=True, verbose_name='مشخصات فنی خودرو ')),
                ('uses', models.CharField(blank=True, max_length=200, null=True, verbose_name='موارد استفاده')),
                ('dimension', models.CharField(blank=True, max_length=200, null=True, verbose_name='ابعاد(میلیمتر)(ارتفاع*عرض*طول)')),
                ('chassis', models.CharField(max_length=100, verbose_name='شاسی')),
                ('extinguishing_system', models.TextField(blank=True, null=True, verbose_name='سیستم اطفا')),
                ('water_pump', models.CharField(blank=True, max_length=200, null=True, verbose_name='پمپ آب')),
                ('water_tank', models.CharField(blank=True, max_length=500, null=True, verbose_name='مخزن آب')),
                ('foam_tank', models.CharField(blank=True, max_length=200, null=True, verbose_name='مخزن فوم')),
                ('monitor', models.CharField(blank=True, max_length=500, null=True, verbose_name='مانیتور')),
                ('hose_reel', models.CharField(blank=True, max_length=500, null=True, verbose_name='هوزریل')),
                ('cabin', models.TextField(verbose_name='کابین')),
                ('roller_shutter', models.CharField(blank=True, max_length=300, null=True, verbose_name='کرکره ها')),
                ('powder_system', models.TextField(blank=True, null=True, verbose_name='سیستم پودر')),
                ('equipment', models.TextField(verbose_name='تجهیزات')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.image', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'خودرو آتش نشانی',
                'verbose_name_plural': 'خودرو های آتش نشانی',
            },
        ),
    ]
