# Generated by Django 4.2.6 on 2023-10-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_contactus_vehicletitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactMe',
        ),
    ]
