# Generated by Django 4.2.6 on 2023-10-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_rename_contactus_contactme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='ContactUs',
        ),
    ]
