# Generated by Django 4.2.6 on 2023-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_rename_contactme_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefightingvehicle',
            name='image_for_title',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='media1/', verbose_name='عکس اصلی'),
        ),
    ]
