# Generated by Django 4.2.6 on 2023-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_rename_image_title_municipalityvehicle_image_for_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefightingvehicle',
            name='img',
            field=models.ManyToManyField(to='mainpage.image', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='image_for_title',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='img',
            field=models.ManyToManyField(to='mainpage.image', verbose_name='عکس'),
        ),
    ]
