# Generated by Django 4.2.6 on 2023-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_firefightingvehicle_img_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefightingvehicle',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='exit', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس'),
        ),
    ]
