# Generated by Django 4.2.6 on 2023-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_firefightingvehicle_img_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firefightingvehicle',
            old_name='image_for_title',
            new_name='image_title',
        ),
        migrations.RenameField(
            model_name='municipalityvehicle',
            old_name='image_for_title',
            new_name='image_title',
        ),
    ]
