# Generated by Django 4.2.6 on 2023-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_rename_image_for_title_firefightingvehicle_image_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(blank=True, max_length=100, null=True, verbose_name='شاسی')),
                ('chassis_english', models.CharField(blank=True, max_length=150, null=True, verbose_name='شاسی به انگلیسی')),
                ('sick_cabin', models.TextField(blank=True, null=True, verbose_name='کابین بیمار')),
                ('electricity_lighting_system', models.TextField(blank=True, null=True, verbose_name='سیستم برق و روشنایی ')),
                ('cooling_heating_system', models.CharField(blank=True, max_length=400, null=True, verbose_name='سیستم سرمایش و گرمایش ')),
                ('ambulance_signs', models.TextField(blank=True, null=True, verbose_name='سیستم آلارم و آژیر و علائم ظاهری آمبولانس')),
                ('medical_equipment', models.TextField(blank=True, null=True, verbose_name='تجهیزات پزشکی')),
            ],
            options={
                'verbose_name': 'خودرو آمبولانس',
                'verbose_name_plural': 'خودرهای آمبولانس',
            },
        ),
    ]
