# Generated by Django 4.2.6 on 2023-11-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_ambulancevehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancevehicle',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی'),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها'),
        ),
    ]
