# Generated by Django 4.2.6 on 2023-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_ambulancevehicle_image_title_ambulancevehicle_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancevehicle',
            name='slug',
            field=models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url'),
        ),
    ]
