# Generated by Django 4.2.6 on 2023-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_ambulancevehicle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی')),
                ('pump_model', models.CharField(max_length=100, verbose_name='مدل پمپ')),
                ('pump_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع پمپ')),
                ('body_material', models.CharField(blank=True, max_length=300, null=True, verbose_name='جنس بدنه پمپ')),
                ('shaft_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='جنس شفت')),
                ('Kind_butterfly', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس پروانه')),
                ('flow_direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='جهت گردش')),
                ('maximum_pressure', models.CharField(blank=True, max_length=300, null=True, verbose_name='حداکثر فشار بسته')),
                ('Output_flow_rate', models.CharField(blank=True, max_length=400, null=True, verbose_name='دبی خروجی')),
                ('required_distance', models.CharField(blank=True, max_length=150, null=True, verbose_name='دور مورد نیاز پمپ')),
                ('Vacuum_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع خلاء')),
                ('preparation_speed', models.CharField(blank=True, max_length=100, null=True, verbose_name='سرعت آماده سازی پمپ')),
                ('maximum_suction_depth', models.CharField(blank=True, max_length=50, null=True, verbose_name='حداکثر عمق مکش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('img', models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها')),
            ],
            options={
                'verbose_name': 'پمپ آتش نشانی',
                'verbose_name_plural': 'پمپ های آتش نشانی',
            },
        ),
    ]
