# Generated by Django 4.2.6 on 2023-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='slug',
            field=models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url'),
        ),
    ]
